version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: paolino53
      MARIADB_DATABASE: loginsystem
      MARIADB_USER: appuser
      MARIADB_PASSWORD: paolino53
      TZ: Europe/Rome
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword # Nota: Questa password dovrebbe corrispondere a MARIADB_ROOT_PASSWORD
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:

